CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
AUDIO_TOKEN_INDEX = -300
DEFAULT_AUD_TOKEN = "<audio>"
DEFAULT_AUD_PATCH_TOKEN = "<aud_patch>"
DEFAULT_AUD_START_TOKEN = "<aud_start>"
DEFAULT_AUD_END_TOKEN = "<aud_end>"
